version: "3"

silent: true

vars:
  DOTNET_SDK_IMAGE: mcr.microsoft.com/dotnet/sdk:7.0
  DOCKER_RUN: docker run -it --rm -p 8000:80 -v $(PWD):/app -w /app
  DOCKER_RELEASE_IMAGE: dotnet-app

tasks:
  dev:
    cmds:
      - "{{.DOCKER_RUN}} {{.DOTNET_SDK_IMAGE}} dotnet watch run --launch-profile dev"

  preview:
    cmds:
      - docker build . -t {{.DOCKER_RELEASE_IMAGE}}:latest
      - docker run -it --rm -p 8080:80 -e ASPNETCORE_URLS=http://+80 {{.DOCKER_RELEASE_IMAGE}}

  cli:
    cmds:
      # Create a project with: task cli -- new web
      # Any other command with: task cli -- ...
      - "{{.DOCKER_RUN}} {{.DOTNET_SDK_IMAGE}} dotnet {{.CLI_ARGS}}"
