version: "3"

silent: true

vars:
  DOCKER_IMAGE_DOTNET_SDK: mcr.microsoft.com/dotnet/sdk:7.0
  DOTNET_DEV_ENV_VARS: ASPNETCORE_URLS=http://+:80 -e ASPNETCORE_ENVIRONMENT=Development
  DOCKER_RUN_DOTNET_CLI: docker run -it --rm -p 8000:80 -v $(PWD):/app -w /app -e {{.DOTNET_DEV_ENV_VARS}}

tasks:
  dev:
    cmds:
      - "{{.DOCKER_RUN_DOTNET_CLI}} {{.DOCKER_IMAGE_DOTNET_SDK}} dotnet watch run --no-launch-profile"

  build:
    cmds:
      - "{{.DOCKER_RUN_DOTNET_CLI}} {{.DOCKER_IMAGE_DOTNET_SDK}} dotnet build --no-launch-profile"

  cli:
    cmds:
      # Create a project with: task cli -- new web
      # Any other command with: task cli -- ...
      - "{{.DOCKER_RUN_DOTNET_CLI}} {{.DOCKER_IMAGE_DOTNET_SDK}} dotnet {{.CLI_ARGS}}"
